export const USER_SIGNIN_API = 'USER_SIGNIN_API';
export const USER_SIGNUP_API = 'USER_SIGNUP_API'
export const USLOGIN = 'USLOGIN';


//------------get Project category-------
export const GET_ALL_PROJECT_CATEGORY_SAGA = 'GET_ALL_PROJECT_CATEGORY_SAGA';
export const GET_ALL_PROJECT_CATEGORY = 'GET_ALL_PROJECT_CATEGORY'
export const GET_LIST_PROJECT_SAGA = 'GET_LIST_PROJECT_SAGA'
export const GET_LIST_PROJECT = 'GET_LIST_PROJECT'

export const OPEN_FORM_EDIT = 'OPEN_FORM_EDIT'
export const SET_SUBMIT_EDIT = 'SET_SUBMIT_EDIT'