export const CREATE_TASK_SAGA = 'CREATE_TASK_SAGA'

export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA'
export const GET_TASK_DETAIL = 'GET_TASK_DETAIL'

export const UPDATE_STATUS_TASK_SAGA = 'UPDATE_STATUS_TASK_SAGA'

export const CHANGE_TASK_MODAL = 'CHANGE_TASK_MODAL'
export const CHANGE_TASK_ASSIGNESS = 'CHANGE_TASK_ASSIGNESS'

export const REMOVE_USER_ASSIGN = 'REMOVE_USER_ASSIGN'

export const HANDLE_CHANGE_POST_API_SAGA = 'HANDLE_CHANGE_POST_API_SAGA'

export const INSERT_COMMENT_TASK_SAGA = 'INSERT_COMMENT_TASK_SAGA'
export const DELETE_COMMENT_TASK_SAGA = 'DELETE_COMMENT_TASK_SAGA'
export const UPDATE_COMMENT_TASK_SAGA = 'UPDATE_COMMENT_TASK_SAGA'
