export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA';
export const GET_USER_BY_PROJECT_ID = 'GET_USER_BY_PROJECT_ID';

export const GET_USER_CYBER_API ='GET_USER_CYBER_API';
export const GET_USER_CYBER ='GET_USER_CYBER';

export const DELETE_USER_CYBER_API = 'DELETE_USER_CYBER_API'
export const EDIT_USER_CYBER_API = 'EDIT_USER_CYBER_API'

export const GET_USER_EDIT_CYBER = 'GET_USER_EDIT_CYBER'
